// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6vuJ0Cy-0gMCQdZYMr6vRZnmtQRReGRs',
    appId: '1:690531175176:web:4a756573f8708223133abd',
    messagingSenderId: '690531175176',
    projectId: 'move-app-2a58b',
    authDomain: 'move-app-2a58b.firebaseapp.com',
    storageBucket: 'move-app-2a58b.firebasestorage.app',
    measurementId: 'G-90Y92C5MZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAxSCcDZiU91bjHMjX0LUBpI4YAXbSijU',
    appId: '1:690531175176:android:26198e6d03216b2d133abd',
    messagingSenderId: '690531175176',
    projectId: 'move-app-2a58b',
    storageBucket: 'move-app-2a58b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxzY88lWE1O-DA7JehX8Fr1vuWWiGimuk',
    appId: '1:690531175176:ios:06dba8a998d47f52133abd',
    messagingSenderId: '690531175176',
    projectId: 'move-app-2a58b',
    storageBucket: 'move-app-2a58b.firebasestorage.app',
    iosBundleId: 'com.moviesapp.flutter.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxzY88lWE1O-DA7JehX8Fr1vuWWiGimuk',
    appId: '1:690531175176:ios:06dba8a998d47f52133abd',
    messagingSenderId: '690531175176',
    projectId: 'move-app-2a58b',
    storageBucket: 'move-app-2a58b.firebasestorage.app',
    iosBundleId: 'com.moviesapp.flutter.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6vuJ0Cy-0gMCQdZYMr6vRZnmtQRReGRs',
    appId: '1:690531175176:web:4a7deadec57d10b1133abd',
    messagingSenderId: '690531175176',
    projectId: 'move-app-2a58b',
    authDomain: 'move-app-2a58b.firebaseapp.com',
    storageBucket: 'move-app-2a58b.firebasestorage.app',
    measurementId: 'G-5NECB972CK',
  );
}
